version: "3"
services:

  frontend:
    container_name: martes-frontend
    build: 
        context: https://github.com/picturestone/martes-backend.git#develop
        dockerfile: Dockerfile
    ports: 
      - 7000:7000

  postgres:
    container_name: martes-postgres
    image: martes-postgres
    build: 
        context: .
        dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  wiki:
    container_name: martes-wiki
    image: requarks/wiki:2
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - wiki:/wiki/data/content

volumes:
  postgres:
  wiki: